name: Build and Deploy to GKE

on:
  pull_request:
    types:
      - closed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: linu-cluster    # Add your cluster name here.
  GKE_ZONE: asia-south1-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: python-app # Add your deployment name here.
  IMAGE: python-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker asia-south1-docker.pkg.dev

      - uses: 'google-github-actions/auth@v1'
        with:
          service_account: '${{ secrets.GKE_SA_AC}}'
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          credentials: ${{ secrets.GKE_SA_KEY }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ secrets.GKE_PROJECT }}
          location: ${{ env.GKE_ZONE }}

      # Build the Docker image
      - name: Build
        run: |-
          DOCKER_TAG=$(git rev-parse --short HEAD)
          docker build \
            --tag "asia-south1-docker.pkg.dev/$PROJECT_ID/linu-poc-repo/$IMAGE:$DOCKER_TAG" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Cloud Registry
      - name: Publish
        run: |-
          DOCKER_TAG=$(git rev-parse --short HEAD)
          docker push "asia-south1-docker.pkg.dev/$PROJECT_ID/linu-poc-repo/$IMAGE:$DOCKER_TAG"

      # Check if the pull request is merged to the master branch and has the release tag
      - name: Check PR Merge and Tag
        id: check_pr_merge_tag
        if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'refs/tags/release-') && github.ref == 'refs/heads/master'
        run: |
          echo "PR merged to master branch with the release tag. Proceeding with deployment."
          echo "::set-output name=deploy::true"
          echo "::set-output name=tag::${{ github.event.pull_request.head.ref }}"
          echo "Release tag: ${{ github.event.pull_request.head.ref }}"

      # Deploy the Docker image to the GKE cluster if the PR is merged to the master branch and has the release tag
      - name: Deploy
        if: steps.check_pr_merge_tag.outputs.deploy == 'true'
        run: |
          DOCKER_TAG=$(git rev-parse --short HEAD)
          sed -i -e "s/GITHUB_SHA/$DOCKER_TAG/" ${{ github.workspace }}/.github/manifests/deployment.yaml
          kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}
          # kubectl apply --force -f ${{ github.workspace }}/.github/manifests/deployment.yaml || (echo "Deployment failed" && exit 1)
