name: Deploy to GKE and Push to Artifact Registry

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for merged PR
        id: pr-check
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          pr_response=$(curl -sSL -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number")
          pr_merged=$(echo "$pr_response" | jq -r .merged)
          pr_ref=$(echo "$pr_response" | jq -r .base.ref)

          if [[ "$pr_merged" == "true" && "$pr_ref" == "release/"* ]]; then
            echo "PR merged with a release tag"
            echo "::set-output name=should-deploy::true"
          else
            echo "PR not merged with a release tag. Skipping deployment and image push."
            echo "::set-output name=should-deploy::false"
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GCP environment
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-poc-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Authenticate to GKE
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_ZONE }}

      - name: Apply manifest file and rollout restart
        if: ${{ needs.pr-check.outputs.should-deploy == 'true' }}
        run: |
          kubectl apply -f .github/deploy/deployment.yaml -n ${{ env.GKE_NAMESPACE }}
          kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.GKE_NAMESPACE }}
