# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: linu-cluster    # Add your cluster name here.
  GKE_ZONE: asia-south1-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: python-app # Add your deployment name here.
  IMAGE: python-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker asia-south1-docker.pkg.dev

    - uses: 'google-github-actions/auth@v1'
      with:
          service_account: '${{ secrets.GKE_SA_AC}}'
          credentials_json: '${{ secrets.GKE_SA_KEY }}'


    # Get the GKE credentials so we can deploy to the cluster
    - uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        credentials: ${{ secrets.GKE_SA_KEY }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        project_id: ${{ secrets.GKE_PROJECT }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build and Push Docker Image
      run: |
        echo "::set-output name=image_tag::asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-poc-repo/$IMAGE:${{ github.run_id }}"
        docker build -t "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-poc-repo/$IMAGE:${{ github.run_id }}" .
        docker push "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-poc-repo/$IMAGE:${{ github.run_id }}"


    # Set up kustomize
    # - name: Set up Kustomize
    #   run: |-
    #     curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
    #     chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        sed -i -e 's/GITHUB_SHA/'"${{ github.sha }}"'/' ${{ github.workspace }}/.github/manifests/deployment.yaml
        kubectl apply -f ${{ github.workspace }}/.github/manifests/deployment.yaml
